#!/bin/bash

while [[ "$#" -gt 0 ]]; do
	case $1 in
	-d|--decrypt)
		mode="decrypt"
		;;
	-e|--encrypt)
		mode="encrypt"
		;;
	-k|--key)
		keyfile="$2"
		shift
		;;
	-h|--help|-?)
		cat <<-EOS >&2
			Usage: $(basename $0) [--encrypt|--decrypt] [--key KEYFILE]

			Options:
			-d, --decrypt   Decrypt the value on STDIN (default mode)
			-e, --encrypt   Encrypt the value on STDIN
			-k, --key       Path to the key file (default: $(pwd)/certs/v2_key)

			-h, --help, -?  Display help
		EOS
		exit 0
		;;
	*)
		echo "ERROR: Unknown parameter passed: $1" >&2
		exit 1
		;;
	esac
	shift
done

mode=${mode:-"decrypt"}
keyfile=${keyfile:-"$(pwd)/certs/v2_key"}

if [ ! -r "$keyfile" ]; then
	echo "ERROR: Cannot read v2 key file: $keyfile" >&2
	exit 1
fi

algorithm="$(grep :algorithm: "$keyfile" | cut -d ' ' -f 2)"
if [ "$algorithm" != "aes-256-cbc" ]; then
	echo "ERROR: Invalid v2 key file: $keyfile" >&2
	exit 1
fi

if [ -n "$DEBUG" ]; then
	cat <<-EOS >&2
		==============================================================================
		Mode:         $mode
		Key File:     $keyfile
		Algorithm:    $algorithm
		IV (Base64):  $(grep :iv: "$keyfile" | cut -d ' ' -f 2)
		IV (Hex):     $(grep :iv: "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)
		Key (Base64): $(grep :key: "$keyfile" | cut -d ' ' -f 2)
		Key (Hex):    $(grep :key: "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)
		==============================================================================
	EOS
fi

case $mode in
decrypt)
	(
		xargs -L1 echo | \
		sed 's/^.\{4\}//;s/.$//' | \
		openssl enc \
			-d \
			-base64 \
			-$algorithm \
			-iv "$(grep :iv:  "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)" \
			-K  "$(grep :key: "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)"
	) < /dev/stdin
	;;
encrypt)
	(
		xargs -L1 echo -n | \
		openssl enc \
			-base64 \
			-$algorithm \
			-iv "$(grep :iv:  "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)" \
			-K  "$(grep :key: "$keyfile" | cut -d ' ' -f 2 | base64 -d | xxd -p -c256)" | \
		sed "s/^/v2:{/;s/$/}/" | \
		xargs -L1 echo -n
	) < /dev/stdin
	;;
*)
	echo "ERROR: Invalid mode: $mode" >&2
	exit 1
esac
